// ── ORIGINAL data/index.ts — BACKUP ──────────────────────────────────────────
// This is the original file before any changes were made
// Saved as backup on 2026-03-19

export const navItems = [
  { name: "About", link: "#about" },
  { name: "Projects", link: "#projects" },
  { name: "all my services ", link: "#whatIdo" },
  { name: "My approach ", link: "#myApproach" },
  { name: "Contact", link: "#contact" },
];

export const navItemsArabic = [
  { name: "نبذة عني", link: "#about" },
  { name: "المشاريع", link: "#projects" },
  { name: "الأفكار", link: "#testimonials" },
  { name: "أفضل تطبيق", link: "#contact" },
  { name: "الجوال", link: "#contact" },
  { name: "نهجي", link: "#contact" },
  { name: "اتصل بنا", link: "#contact" },
];

export const navItemsFrench = [
  { name: "À propos", link: "#about" },
  { name: "Projets", link: "#projects" },
  { name: "Idées", link: "#testimonials" },
  { name: "Meilleure application", link: "#contact" },
  { name: "Mobile", link: "#contact" },
  { name: "Mon approche", link: "#contact" },
  { name: "Contact", link: "#contact" },
];

export const gridItems = [
  {
    id: 1,
    title: "I prioritize client collaboration, fostering open communication ",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "./b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "I'm very flexible with time zone communications",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "My tech stack",
    description: "I constantly try to improve",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Tech enthusiast with a passion for development.",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "./grid.svg",
    spareImg: "./b4.svg",
  },
  {
    id: 5,
    title: "I can develop the front-end of your applications. ",
    description: "This text is targeted towards tech companies.",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
    titleClassName: "justify-center md:justify-start lg:justify-center",
    img: "./b5.svg",
    spareImg: "./grid.svg",
  },
  {
    id: 6,
    title: "Do you want to start a project together?",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const gridItemsArabic = [
  {
    id: 1,
    title: "أُعطي الأولوية للتعاون مع العميل، وتعزيز التواصل المفتوح.",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "./b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "أستطيع العمل مع مناطق مختلفة حول العالم",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "التقنيات التي يمكن العمل بها",
    description: "احاول التطوير من نفسي بشكل مستمر",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "احاول جاهدا ان اطور من نفسي",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "./grid.svg",
    spareImg: "./b4.svg",
  },
  {
    id: 5,
    title: "يمكنني تطوير الواجهة الأمامية لتطبيقاتك.",
    description: "هذا النص موجه لشركات البرمجة",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
    titleClassName: "justify-center md:justify-start lg:justify-center",
    img: "./b5.svg",
    spareImg: "./grid.svg",
  },
  {
    id: 6,
    title: "هل تريد أن نبدأ مشروعًا معًا؟",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const gridItemsFrench = [
  {
    id: 1,
    title: "Je privilégie la collaboration avec le client, en favorisant une communication ouverte. ",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "./b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "Je suis très flexible en matière de communication entre fuseaux horaires.",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "Ma stack technologique",
    description: "Je cherche constamment à m'améliorer.",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Passionné de technologie avec une passion pour le développement.",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "/grid.svg",
    spareImg: "./b4.svg",
  },
  {
    id: 5,
    title: "Je peux développer le front-end de vos applications.",
    description: "This text is targeted towards tech companies.",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
    titleClassName: "justify-center md:justify-start lg:justify-center",
    img: "./b5.svg",
    spareImg: "./grid.svg",
  },
  {
    id: 6,
    title: "Voulez-vous démarrer un projet ensemble ?",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const products2 = [
  { title: "Moonbeam", link: "#", thumbnail: "./restraunt1.png" },
  { title: "Cursor", link: "#", thumbnail: "./Ecomeerce Shop For serveral Projects.png" },
  { title: "Rogue", link: "#", thumbnail: "./restraunt1.png" },
  { title: "Editorially", link: "#", thumbnail: "./SimpleBootstrap.png" },
  { title: "Editrix AI", link: "#", thumbnail: "./Book-store.png" },
  { title: "Pixel Perfect", link: "#", thumbnail: "./Cake-shope-scss.png" },
  { title: "Algochurn", link: "#", thumbnail: "./AdvancedEcomercceCite.png" },
  { title: "Aceternity UI", link: "#", thumbnail: "./booking housees.png" },
  { title: "Tailwind Master Kit", link: "#", thumbnail: "./car repair services.png" },
  { title: "SmartBridge", link: "#", thumbnail: "./coffe shop.png" },
  { title: "Renderwork Studio", link: "#", thumbnail: "./ecommerce--shop.png" },
  { title: "Creme Digital", link: "#", thumbnail: "./building--app.png" },
  { title: "Golden Bells Academy", link: "#", thumbnail: "./carpenter--shop.png" },
  { title: "Invoker Labs", link: "#", thumbnail: "./car repaired shop.png" },
  { title: "E Free Invoice", link: "", thumbnail: "./Mobile App Presentation.png" },
  { title: "Aceternity UI", link: "#", thumbnail: "./admin-dashboard---2.png" },
  { title: "Tailwind Master Kit", link: "#", thumbnail: "./Book-store.png" },
  { title: "SmartBridge", link: "#", thumbnail: "./building--app.png" },
  { title: "Renderwork Studio", link: "#", thumbnail: "./car app using api to fetch cars.png" },
  { title: "Creme Digital", link: "#", thumbnail: "./ecommerce--shop.png" },
  { title: "Golden Bells Academy", link: "#", thumbnail: "./fast food delivery.png" },
  { title: "Invoker Labs", link: "#", thumbnail: "./carpenter--shop.png" },
  { title: "E Free Invoice", link: "", thumbnail: "./graphic designer 22 potfolio.png" },
  { title: "HooBankDesign.png", link: "#", thumbnail: "./carpenter--shop.png" },
  { title: "Invoker Labs", link: "#", thumbnail: "./ModernPortfolio Website.png" },
  { title: "E Free Invoice", link: "", thumbnail: "./mehcanics store.png" },
  { title: "Aceternity UI", link: "#", thumbnail: "./ui for Platform to showcase a profuct of company.png" },
  { title: "Tailwind Master Kit", link: "#", thumbnail: "./restraunt1.png" },
  { title: "SmartBridge", link: "#", thumbnail: "./rent car 2.png" },
  { title: "Renderwork Studio", link: "#", thumbnail: "./photo grapher potfolio.png" },
  { title: "Creme Digital", link: "#", thumbnail: "./painting shop.png" },
  { title: "Golden Bells Academy", link: "#", thumbnail: "./Modern Jquery potfolio.png" },
  { title: "Invoker Labs", link: "#", thumbnail: "./Kasper.png" },
  { title: "E Free Invoice", link: "", thumbnail: "./Book-store.png" },
];

export const projects = [
  {
    id: 1,
    title: "personal dashboard ui to manage your clients and tasks and statistics of your work ",
    titleArab: "لوحة معلومات شخصية لإدارة عملائك ومهامك وإحصائيات عملك",
    titleFrench: "Tableau de bord personnel pour gérer vos clients, tâches et statistiques de votre travail.",
    des: "A complex UI design implemented using HTML and advanced CSS concepts such as animation, Grid, and Flexbox, ensuring full responsiveness.",
    desArab: "تصميم واجهة مستخدم معقدة تم تنفيذه باستخدام HTML ومفاهيم CSS المتقدمة flex box و Grid",
    desFrecnh: "Une conception d'interface utilisateur complexe implémentée à l'aide de HTML et de concepts CSS avancés tels que l'animation, Grid et Flexbox, garantissant une pleine réactivité.",
    img: "./managementDashboard.png",
    link: " https://tidjani1bachir.github.io/tempalte-4/",
  },
  {
    id: 2,
    title: "Template2",
    titleArab: "نموذج 2",
    titleFrench: "Modèle 3",
    des: "A Next.js template leveraging Mux for video hosting. using vanilla css and fully responsive",
    desArab: "قالب Next.js يستخدم Mux لاستضافة مقاطع الفيديو. يمكنني إنشاء تطبيق Next.js مخصص لعرض مقاطع الفيديو الخاصة بك.",
    desFrecnh: "Modèle Next.js qui utilie Mux pour l'hébergement vidéo. Je peux créer une application Next.js personnalisée pour mettre en valeur vos vidéos.",
    img: "./Kasper.png",
    link: "https://tidjani1bachir.github.io/Implimentation-Template-Kasper-html-css/",
  },
  {
    id: 3,
    title: "Hang man game",
    titleArab: "لعبة الرجل المشنوق",
    titleFrench: "Jeu du pendu",
    des: "Hangman game built using vanilla JavaScript, featuring a popup library for displaying game results and fetching data from a JSON file.",
    desArab: "لعبة JavaScript Vanilla",
    desFrecnh: "Jeu JavaScript vanille utilisant une bibliothèque popup et récupérant des données depuis un fichier JSON.",
    img: "./hang-man-game.png",
    link: "https://tidjani1bachir.github.io/hangMan-Game-vanilla-Java-Script/",
  },
  {
    id: 4,
    title: "Telmplate3",
    titleArab: "نموذخ 3",
    titleFrench: "Modèle 3",
    des: "Template 3 is a fully-featured web application design, incorporating key components such as payment sections, testimonials, hero content, landing pages, team information, contact details, video embeds, services, team members, events, and a scroll-to-top button.",
    desArab: "القالب 3 عبارة عن تنفيذ تصميم شامل يضم مكونات أساسية لتطبيق الويب.",
    desFrecnh: "Le modèle 3 est une implémentation de design complète comprenant des composants essentiels d'applications web.",
    img: "./Template 3.png",
    link: "https://tidjani1bachir.github.io/Template-For-Store/",
  },
  {
    id: 5,
    title: "Tic-Tac-Toe ",
    titleArab: "تيك تاك تو",
    titleFrench: "Tic-Tac-Toe",
    des: "A simple game built with TypeScript and Next.js, featuring a result display that shows whether the cross wins, loses, or x wins ,loses or draw.",
    desArab: "لعبة بسيطة باستخدام typeScript وNextjs",
    desFrecnh: "Jeu simple utilisant TypeScript et Next.js",
    img: "./XAndOGame.png",
    link: "https://tidjani1bachir.github.io/Tic-Tac-Toe/",
  },
  {
    id: 6,
    title: "Bondi",
    titleArab: "بوندي",
    titleFrench: "Bondi",
    des: "Implementation of a simple web design using the Bootstrap Toolkit ",
    desArab: "تنفيذ تصميم ويب بسيط باستخدام مكتبة Bootstrap",
    desFrecnh: "Implémentation d'un design web simple utilisant la bibliothèque Bootstrap",
    img: "./SimpleBootstrap.png",
    link: "https://tidjani1bachir.github.io/Bondi/",
  },
  {
    id: 7,
    title: "Cars App",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "Next.js app fetching car data and images via APIs. Uses TypeScript for type safety, Headless UI for modern UI, and client-side rendering for dynamic updates.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./carshowcase1111.png",
    link: "/https://tidjani1bachir.github.io/Cars-agency/",
  },
  {
    id: 8,
    title: "Admin dashboard",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "A prototype of a React admin panel application designed to help organize your data. It offers 6 beautiful themes, with the option to toggle between light and dark modes.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./adminApp.png",
    link: "https://react-admin-dashboard-rbrf.vercel.app",
  },
  {
    id: 9,
    title: "Lawyer platforme idea presentation",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "A service platform for lawyers and legal consultants, presented as a concept using Next.js and Tailwind CSS components.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./avocat.png",
    link: "https://prsentation-lawyer-of-platform-996x.vercel.app",
  },
  {
    id: 10,
    title: "Node Js Application",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "A Node.js application for performing CRUD operations using Next.js for server-side rendering.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./CRUDNodeJs.png",
    link: "https://basic-crud-nine.vercel.app",
  },
  {
    id: 11,
    title: " samll Ecommerce",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "A React small E Commerce website that utilizes a JavaScript file as a database, featuring advanced filtering functionality.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./ecommerce.png",
    link: "https://samll-e-commerce-website.vercel.app",
  },
  {
    id: 12,
    title: "Modern Service presentation platforme",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "A Next.js application focused solely on the frontend, implementing a modern design to showcase services offered by a specific organization.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./modernSaaS.png",
    link: "https://modern-saas-ptototype.vercel.app",
  },
  {
    id: 14,
    title: "xora",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "Xora is a modern business website built with React.js and Tailwind CSS. It features an animated pricing section, a contemporary FAQ section, and a demo download area.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./xora.png",
    link: "https://tidjani1bachir.github.io/xora/",
  },
  {
    id: 15,
    title: "Ecommerce website prototype",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "Next.js modern online store for showcasing products to sell.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./EcomPrototype.png",
    link: "https://modern-ecommerce-prototype.vercel.app",
  },
  {
    id: 16,
    title: "cars Applcation",
    titleArab: "تطبيق سيارات",
    titleFrench: "Application Voitures",
    des: "Next.js app fetching car data and images via APIs. Uses TypeScript for type safety, Headless UI for modern UI.",
    desArab: "تطبيق Next.js يقوم بجلب بيانات وصور السيارة عبر واجهات برمجة التطبيقات.",
    desFrecnh: "Application Next.js qui récupere les données et images des voitures via des API.",
    img: "./carshowcase1111.png",
    link: "https://cars-api-nine.vercel.app",
  },
];

export const testimonials = [
  {
    quote: "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote: "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote: "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote: "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote: "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
];

export const companies = [
  { id: 1, name: "cloudinary", img: "./cloud.svg", nameImg: "./cloudName.svg" },
  { id: 2, name: "appwrite", img: "./app.svg", nameImg: "./appName.svg" },
  { id: 3, name: "HOSTINGER", img: "./host.svg", nameImg: "./hostName.svg" },
  { id: 4, name: "stream", img: "./s.svg", nameImg: "./streamName.svg" },
  { id: 5, name: "docker.", img: "./dock.svg", nameImg: "./dockerName.svg" },
];

export const workExperience = [
  {
    id: 1,
    title: "Desktop application",
    titleArab: "تطبيق سطح المكتب",
    titleFrecn: "Application de bureau",
    desc: "i can create Desktop Apps with javascript Frameworks like Electron js and tauri",
    descArab: "يمكنني إنشاء تطبيقات سطح المكتب باستخدام أطر عمل Java و C++ و JavaScript لتطبيقات سطح المكتب مثل Electron JS و Tauri",
    descFrench: "je peux créer des applications de bureau avec Java et C++ et des frameworks JavaScript pour les applications de bureau comme Electron JS et Tauri",
    className: "md:col-span-2",
    thumbnail: "./exp2.svg",
  },
  {
    id: 2,
    title: "FULL web Application",
    titleArab: "تطبيقات كاملة (mySQL and react or Next Js Stack)",
    titleFrecn: "تطبيقات MySQL كاملة",
    desc: "i can work on api projects for dynamicly sholwnig content or informations like Currency prices cars information ,maps,and more",
    descArab: "",
    descFrench: "",
    className: "md:col-span-2",
    thumbnail: "./exp3.svg",
  },
  {
    id: 3,
    title: "FULL web Application",
    titleArab: "تطبيقات كاملة (mySQL and react or Next Js Stack)",
    titleFrecn: "تطبيقات MySQL كاملة",
    desc: "i can create FULL Stack application with MERN Stack and php And Mysql",
    descArab: "",
    descFrench: "",
    className: "md:col-span-2",
    thumbnail: "./exp1.svg",
  },
  {
    id: 4,
    title: "Mobile applications",
    titleArab: "تطبيقات الهاتف",
    titleFrecn: "Applications Mobiles",
    desc: "i can create full stack Mobile applications using React native for both android and ios (cross platform) and native android applications using android studio with java ",
    descArab: "يمكنني إنشاء تطبيقات جوال كاملة باستخدام React native لكل من android و ios (منصة متعددة) و android studio مع java مع fire Base أو SQL Lite",
    descFrench: "je peux créer des applications mobiles full stack en utilisant React native pour Android et iOS (multiplateforme) et Android Studio avec Java avec Fire Base ou SQL Lite",
    className: "md:col-span-2",
    thumbnail: "./exp4.svg",
  },
];

export const socialMedia = [
  { id: 1, img: "./git.svg", link: "https://github.com/Tidjani1Bachir" },
  { id: 3, img: "./link.svg", link: "https://www.linkedin.com/in/tidjani-bachir-b27861226/" },
];